scripts/issue6ColumnaModificarStock.sql
src/main/java/sic/modelo/Nota.java
src/main/java/sic/modelo/NotaCredito.java
src/main/java/sic/service/impl/NotaServiceImpl.java

Agrega el script para agregar el campo informativo sobre modificació de stock a la db sobre NC. Realiza los cambios en los services para volvel el stock al estado anterior a la nota de credito por devolucion.

Recuperacion del stock al eliminar una NC por devolución.

---

scripts/issue31PagosEnCompras.sql
src/main/java/sic/service/impl/PagoServiceImpl.java

Agrega las correcciones en el service para no dar de alta renglones CC por los pagos en compras. Agrega script para eliminar los renglones CC de pagos en compras.

Pagos en compras

---

src/main/java/sic/controller/CajaController.java
src/main/java/sic/controller/ClienteController.java
src/main/java/sic/controller/FacturaController.java
src/main/java/sic/controller/PagoController.java
src/main/java/sic/controller/PedidoController.java
src/main/java/sic/modelo/Factura.java
src/main/java/sic/modelo/FacturaCompra.java
src/main/java/sic/modelo/FacturaVenta.java
src/main/java/sic/modelo/Pago.java
src/main/java/sic/modelo/Pedido.java
src/main/java/sic/repository/ClienteRepository.java
src/main/java/sic/repository/FacturaRepository.java
src/main/java/sic/service/IClienteService.java
src/main/java/sic/service/IFacturaService.java
src/main/java/sic/service/impl/ClienteServiceImpl.java
src/main/java/sic/service/impl/FacturaServiceImpl.java
src/test/java/sic/builder/PedidoBuilder.java
src/test/java/sic/integration/CuentaCorrienteIntegrationTest.java
src/test/java/sic/integration/FacturacionIntegrationTest.java
src/test/java/sic/modelo/dto/FacturaDTO.java
src/test/java/sic/modelo/dto/FacturaVentaDTO.java
src/test/java/sic/modelo/dto/PagoDTO.java
src/test/java/sic/modelo/dto/PedidoDTO.java

Agrega los endpoints nuevos en relación a los cambios en los models.
Models Afectados:
1. Factura
2. Factura Venta
3. Factura Compra
4. Pago
5. Pedido

Agrega endpoints y modifica los models.

---

scripts/issue51NumeracionNotas.sql
src/main/java/sic/repository/NotaCreditoRepository.java
src/main/java/sic/repository/NotaDebitoRepository.java
src/main/java/sic/service/INotaService.java
src/main/java/sic/service/impl/NotaServiceImpl.java

Corrige los el service de nota para su correcta numeracion. Agrega script para modificar la tabla de notas y corregir las numeracion.

Corrige la numeracion de las notas.

---

src/main/java/sic/controller/CuentaCorrienteController.java
src/main/java/sic/modelo/Cliente.java
src/main/java/sic/modelo/CuentaCorriente.java
src/main/java/sic/repository/RenglonCuentaCorrienteRepository.java
src/main/java/sic/service/ICuentaCorrienteService.java
src/main/java/sic/service/IRenglonCuentaCorrienteService.java
src/main/java/sic/service/impl/ClienteServiceImpl.java
src/main/java/sic/service/impl/CuentaCorrienteServiceImpl.java
src/main/java/sic/service/impl/RenglonCuentaCorrienteServiceImpl.java
src/test/java/sic/builder/ClienteBuilder.java

Modificaciones en los services, models y repositorys de CC y cliente para agregar el ultimo movimiento.

Agrega la funcionalidad de ultimo movimiento.

---

src/main/java/sic/service/impl/FacturaServiceImpl.java
src/test/java/sic/integration/FacturacionIntegrationTest.java

Corrige el pago de facturas con recibos, cuando se está facturando un recibo.

Corrige el pago de facturas con recibos.

---

scripts/issue86CAEenRenglonesCC.sql
src/main/java/sic/modelo/RenglonCuentaCorriente.java
src/main/java/sic/repository/RenglonCuentaCorrienteRepository.java
src/main/java/sic/service/IRenglonCuentaCorrienteService.java
src/main/java/sic/service/impl/FacturaServiceImpl.java
src/main/java/sic/service/impl/NotaServiceImpl.java
src/main/java/sic/service/impl/RenglonCuentaCorrienteServiceImpl.java

Modifica el repository y los services correspondientes para persistir el CAE en los renglones CC. Agrega script para agregar la columna y realizar el backfill.

Agrega CAE a los renglones CC.

---

src/test/java/sic/integration/CuentaCorrienteIntegrationTest.java
src/test/java/sic/modelo/dto/NotaDTO.java

Corrige los DTO de nota y agrega el control de stock luego de la eliminación de una nota de credito.

Agrega al test de CC la eliminación de NC.

---

scripts/issue13NumeroDeCliente.sql
src/main/java/sic/controller/ClienteController.java
src/main/java/sic/modelo/Cliente.java
src/main/java/sic/repository/ClienteRepository.java
src/main/java/sic/service/IClienteService.java
src/main/java/sic/service/impl/ClienteServiceImpl.java
src/test/java/sic/builder/ClienteBuilder.java

Agrega al model de cliente, un numero de cliente asociado en el alta.
Agrega script de backfill para los clientes ya existentes.

Agrega un numero de cliente.

---

src/main/java/sic/controller/UsuarioController.java
src/main/java/sic/service/IUsuarioService.java
src/main/java/sic/service/impl/UsuarioServiceImpl.java

Modificar Usuario

---

src/main/java/sic/controller/ProductoController.java
src/main/java/sic/modelo/dto/ActualizarProductosDTO.java
src/main/java/sic/modelo/dto/ProductosParaActualizarDTO.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java

Agrega el DTO ActualizarProductos.

---

scripts/issue239.sql
src/main/java/sic/controller/UbicacionController.java
src/main/java/sic/modelo/Localidad.java
src/main/java/sic/modelo/Pedido.java
src/main/java/sic/modelo/Ubicacion.java
src/main/java/sic/modelo/dto/UbicacionDTO.java
src/main/java/sic/repository/LocalidadRepository.java
src/main/java/sic/service/IUbicacionService.java
src/main/java/sic/service/impl/UbicacionServiceImpl.java
src/main/resources/Mensajes.properties
src/main/resources/ValidationMessages.properties
src/test/java/sic/builder/UbicacionBuilder.java

Modifica los atributos de ubicacion para que sólo localidad y provicia sean obligatorios.

---

src/main/java/sic/controller/FacturaController.java
src/main/java/sic/controller/NotaController.java
src/main/java/sic/service/ICuentaCorrienteService.java
src/main/java/sic/service/IFacturaService.java
src/main/java/sic/service/INotaService.java
src/main/java/sic/service/impl/CuentaCorrienteServiceImpl.java
src/main/java/sic/service/impl/FacturaServiceImpl.java
src/main/java/sic/service/impl/NotaServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java

Quita la eliminacion de facturas de compra y de venta.

---

src/main/java/sic/controller/ConfiguracionDelSistemaController.java
src/main/java/sic/controller/FacturaController.java
src/main/java/sic/controller/ReciboController.java
src/main/java/sic/modelo/ConfiguracionDelSistema.java
src/main/java/sic/modelo/Factura.java
src/main/java/sic/modelo/Recibo.java
src/main/java/sic/modelo/dto/ConfiguracionDelSistemaDTO.java
src/main/java/sic/modelo/dto/FacturaCompraDTO.java
src/main/java/sic/modelo/dto/FacturaDTO.java
src/main/java/sic/modelo/dto/ReciboDTO.java
src/main/java/sic/service/IConfiguracionDelSistemaService.java
src/main/java/sic/service/impl/CajaServiceImpl.java
src/main/java/sic/service/impl/ConfiguracionDelSistemaServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java

Modifica los POST y PUT de los controllers de Recibo, Factura y Cds.

---

src/main/java/sic/controller/CarritoCompraController.java
src/main/java/sic/repository/CarritoCompraRepository.java
src/main/java/sic/service/CarritoCompraServiceImpl.java
src/main/java/sic/service/ICarritoCompraService.java

Agrega endpoint para devolver el item de carrito de compra por idUsuario e idProducto.

---

src/main/java/sic/controller/GastoController.java
src/main/java/sic/modelo/BusquedaGastoCriteria.java
src/main/java/sic/repository/GastoRepository.java
src/main/java/sic/repository/GastoRepositoryCustom.java
src/main/java/sic/repository/custom/GastoRepositoryImpl.java
src/main/java/sic/service/IGastoService.java
src/main/java/sic/service/impl/GastoServiceImpl.java

Nuevo endpoint para listar gastos. 

---

src/main/java/sic/modelo/Factura.java
src/main/java/sic/modelo/dto/FacturaDTO.java

Agrega al model de Factura el JsonGetter para nro de pedido, y nroPedido en FacturaDTO.

---

src/main/java/sic/controller/NotaController.java

Quita los permisos para crear notas a los roles que no sean administrador o encargado.

---

scripts/issue270.sql
src/main/java/sic/controller/CuentaCorrienteController.java
src/main/java/sic/controller/ProveedorController.java
src/main/java/sic/modelo/BusquedaCuentaCorrienteProveedorCriteria.java
src/main/java/sic/modelo/BusquedaProveedorCriteria.java
src/main/java/sic/modelo/Proveedor.java
src/main/java/sic/modelo/dto/ProveedorDTO.java
src/main/java/sic/repository/ProveedorRepository.java
src/main/java/sic/service/IProveedorService.java
src/main/java/sic/service/impl/CuentaCorrienteServiceImpl.java
src/main/java/sic/service/impl/ProveedorServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java

Quita codigo de proveedor y agrega numero de proveedor que es generado automaticamente.

---

src/main/java/sic/controller/CajaController.java
src/main/java/sic/controller/FormaDePagoController.java
src/main/java/sic/repository/FormaDePagoRepository.java
src/main/java/sic/service/IFormaDePagoService.java
src/main/java/sic/service/impl/FormaDePagoServiceImpl.java

Agrega un metodo en el repository y service para recuperar todas las formas de pago aunque estén eliminadas.

---

src/main/java/sic/controller/ProductoController.java
src/main/java/sic/modelo/BusquedaProductoCriteria.java
src/main/java/sic/service/impl/ProductoServiceImpl.java

Agrega la posibilidad de buscar productos unicamente que se encuentren con stock superior a cero.

---

src/test/java/sic/integration/AppIntegrationTest.java
src/test/resources/data-test.sql

Agrega script para el alta del enviroment de test.

---

src/main/java/sic/service/impl/AfipServiceImpl.java

Modifica y corrige la validacion por cliente sin id fiscal al autorizar un comprobante.

---

src/main/java/sic/service/impl/ReciboServiceImpl.java

Mutea la regla de negocio que impide que una factura se de de alta, con recibos superiores a su total.

---

src/main/java/sic/controller/NotaController.java
src/main/java/sic/modelo/BusquedaNotaCriteria.java
src/main/java/sic/modelo/NotaDebito.java
src/main/java/sic/repository/NotaCreditoRepository.java
src/main/java/sic/repository/NotaDebitoRepository.java
src/main/java/sic/repository/NotaRepository.java
src/main/java/sic/service/INotaService.java
src/main/java/sic/service/impl/NotaServiceImpl.java

Cambia la logica del controller y service de nota para trabajar con la criteria y devolver notas de credito o debito, direfenciando los tipos.

---

scripts/issue309.sql
src/main/java/sic/App.java
src/main/java/sic/controller/PedidoController.java
src/main/java/sic/modelo/Pedido.java
src/main/java/sic/repository/RenglonPedidoRepository.java
src/main/java/sic/service/IPedidoService.java
src/main/java/sic/service/impl/CarritoCompraServiceImpl.java
src/main/java/sic/service/impl/FacturaServiceImpl.java
src/main/java/sic/service/impl/PedidoServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java

Corrige el bug de total actual de pedidos. Cambia a transient ese atributo.

---

src/main/java/sic/controller/FacturaController.java
src/main/java/sic/modelo/ComprobanteAFIP.java
src/main/java/sic/service/IClienteService.java
src/main/java/sic/service/IFacturaService.java
src/main/java/sic/service/impl/AfipServiceImpl.java
src/main/java/sic/service/impl/ClienteServiceImpl.java
src/main/java/sic/service/impl/FacturaServiceImpl.java
src/main/java/sic/service/impl/NotaServiceImpl.java

Modifica el model de ComprobanteAFIP para operar con el cliente desnormalizado en la factura.

---

src/main/java/sic/controller/FacturaController.java
src/main/java/sic/controller/ProductoController.java
src/main/java/sic/modelo/NuevaFacturaVentaDTO.java
src/main/java/sic/modelo/ProductosParaVerificarStock.java
src/main/java/sic/modelo/ProductosParaVerificarStockDTO.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/IReciboService.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/main/java/sic/service/impl/ReciboServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java
src/test/java/sic/service/impl/ProductoServiceImplTest.java

Cambia el alta de Facturas de venta y la consulta por faltantes.

---

src/main/java/sic/controller/FacturaController.java
src/main/java/sic/service/IFacturaService.java
src/main/java/sic/service/impl/AfipServiceImpl.java
src/main/java/sic/service/impl/FacturaServiceImpl.java
src/main/resources/messages.properties
src/test/java/sic/integration/AppIntegrationTest.java

Agrega el envío por email de una factura de venta.

---

src/main/java/sic/controller/AuthController.java
src/main/java/sic/modelo/dto/RegistracionClienteAndUsuarioDTO.java
src/main/java/sic/service/IRegistracionService.java
src/main/java/sic/service/impl/RegistracionServiceImpl.java
src/main/resources/messages.properties
src/test/java/sic/integration/AppIntegrationTest.java

Agrega validaciones al model de registración.

---

src/main/resources/application.properties

Cambio de variables de entorno para la conexion a la DB

---

src/main/java/sic/modelo/dto/ProductosParaActualizarDTO.java
src/main/java/sic/service/impl/ProductoServiceImpl.java

Poder modificar la cantidad venta minima en la modificacion multiple de productos

---

pom.xml
scripts/issue336.sql
src/main/java/sic/modelo/CantidadEnSucursal.java
src/main/java/sic/modelo/Medida.java
src/main/java/sic/modelo/Producto.java
src/test/java/sic/builder/ProductoBuilder.java
src/test/java/sic/controller/FacturaCompraControllerTest.java
src/test/java/sic/controller/PedidoControllerTest.java
src/test/java/sic/integration/AppIntegrationTest.java
src/test/java/sic/model/CantidadEnSucursal.java
src/test/java/sic/model/Producto.java
src/test/java/sic/repository/ProductoRepositoryTest.java
src/test/java/sic/service/impl/MessageSourceImplTest.java

Optimistic locking en la tabla Producto 

---

.travis.yml
pom.xml

Migrar a Java 11 LTS

---

src/main/java/sic/modelo/criteria/BusquedaTraspasoCriteria.java
src/main/java/sic/service/impl/TraspasoServiceImpl.java
src/test/java/sic/service/impl/TraspasoServiceImplTest.java

Agrega a la busqueda de traspasos el nro de pedido.

---

src/main/java/sic/modelo/Usuario.java
src/main/java/sic/repository/UsuarioRepository.java

Agrega a la notation ElementCollection la estrategía EAGER para el fetch.

---

src/main/java/sic/controller/ProductoController.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/main/java/sic/service/impl/TraspasoServiceImpl.java
src/test/java/sic/service/impl/ProductoServiceImplTest.java
src/test/java/sic/service/impl/TraspasoServiceImplTest.java

Agrega test faltantes de traspaso. Modifica el código para construir traspasos.

---

src/main/java/sic/controller/UbicacionController.java
src/main/java/sic/modelo/dto/LocalidadesParaActualizarDTO.java
src/main/java/sic/service/IUbicacionService.java
src/main/java/sic/service/impl/UbicacionServiceImpl.java
src/test/java/sic/controller/UbicacionControllerTest.java
src/test/java/sic/service/impl/UbicacionServiceImplTest.java

Modificación multiple de localidades

---

src/main/java/sic/modelo/criteria/BusquedaReciboCriteria.java
src/main/java/sic/service/impl/ReciboServiceImpl.java
src/test/java/sic/service/impl/ProductoServiceImplTest.java
src/test/java/sic/service/impl/ReciboServiceImplTest.java

Filtro por forma de pago en recibos venta/compra

---

src/main/java/sic/controller/CarritoCompraController.java
src/main/java/sic/service/ICarritoCompraService.java
src/main/java/sic/service/impl/CarritoCompraServiceImpl.java
src/test/java/sic/service/impl/CarritoCompraServiceImplTest.java

Refactoring endpoint "/carrito-compra/clientes/{idCliente}"

---

src/main/java/sic/repository/ClienteRepository.java
src/main/java/sic/repository/GastoRepository.java
src/main/java/sic/repository/PedidoRepository.java
src/main/java/sic/repository/TraspasoRepository.java
src/main/java/sic/service/impl/ClienteServiceImpl.java
src/main/java/sic/service/impl/GastoServiceImpl.java
src/main/java/sic/service/impl/PedidoServiceImpl.java
src/main/java/sic/service/impl/TraspasoServiceImpl.java
src/main/resources/messages.properties
src/test/java/sic/service/impl/ClienteServiceImplTest.java
src/test/java/sic/service/impl/PedidoServiceImplTest.java

Refactoring busqueda duplicados por nro: Pedido, Gasto, Cliente

---

scripts/issues/issue415v2.sql
src/main/java/sic/controller/ProductoController.java
src/main/java/sic/modelo/embeddable/CantidadProductoEmbeddable.java
src/main/java/sic/repository/ProductoRepository.java
src/main/java/sic/repository/RenglonPedidoRepository.java
src/main/java/sic/service/IPedidoService.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/impl/PedidoServiceImpl.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/main/resources/messages.properties
src/test/java/sic/integration/AppIntegrationTest.java
src/test/java/sic/service/impl/PedidoServiceImplTest.java
src/test/java/sic/service/impl/ProductoServiceImplTest.java

Persistir la RESERVA de stock para mejorar performance

---

src/main/java/sic/controller/ProductoController.java
src/main/java/sic/repository/ProductoFavoritoRepository.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/test/java/sic/controller/ProductoControllerTest.java
src/test/java/sic/service/impl/ProductoServiceImplTest.java

Restyling 

---

src/main/java/sic/modelo/criteria/BusquedaProductoCriteria.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/test/java/sic/service/impl/ProductoServiceImplTest.java

Agrega el uso de Order en la busqueda de productos

---

pom.xml

Solucion al exploit CVE-2021-44228 de log4j

Fix exploit log4j

---

.github/workflows/build.yml
pom.xml
src/main/java/sic/service/impl/AfipServiceImpl.java
src/main/resources/application.properties
src/test/java/sic/integration/AppIntegrationTest.java
src/test/java/sic/repository/ProductoRepositoryTest.java
src/test/resources/application.properties
src/test/resources/data.sql
system.properties

Cambia la version de java a 17 y spring boot a 2.6.1

---

src/main/java/sic/controller/SucursalController.java
src/main/java/sic/modelo/dto/NuevaSucursalDTO.java
src/main/java/sic/modelo/dto/SucursalDTO.java
src/main/java/sic/service/IProductoService.java
src/main/java/sic/service/ISucursalService.java
src/main/java/sic/service/impl/ProductoServiceImpl.java
src/main/java/sic/service/impl/SucursalServiceImpl.java
src/test/java/sic/integration/AppIntegrationTest.java
src/test/java/sic/model/NuevaSucursal.java
src/test/java/sic/service/impl/SucursalServiceImplTest.java

Agrega el model NuevaSucursalDTO
#438

Refactoriza el alta de sucursal

---

src/main/java/sic/service/IFacturaVentaService.java
src/main/java/sic/service/impl/FacturaVentaServiceImpl.java
src/test/java/sic/controller/FacturaVentaControllerTest.java

Modify the way that the billing is made, adding a new validation to cross it with the client's debt capacity

---

pom.xml
scripts/issues/issue454.sql
src/main/java/sic/controller/PagoController.java
src/main/java/sic/modelo/Recibo.java
src/main/java/sic/repository/ReciboRepository.java
src/main/java/sic/service/IPagoService.java
src/main/java/sic/service/IReciboService.java
src/main/java/sic/service/impl/MercadoPagoServiceImpl.java
src/main/java/sic/service/impl/NotaServiceImpl.java
src/main/java/sic/service/impl/ReciboServiceImpl.java
src/test/java/sic/service/impl/MercadoPagoServiceImplTest.java
src/test/java/sic/service/impl/ReciboServiceImplTest.java

Update the implementation of MercadoPago

---

pom.xml
src/main/java/sic/controller/AuthController.java
src/main/java/sic/service/IUsuarioService.java
src/main/java/sic/service/impl/UsuarioServiceImpl.java

Remove idSucursal from recovery password endpoint
